### ISSUE TITLE
Missing component - no GUI

### ISSUE THREAD

**Issue by Stephen812** [OpenVPN/openvpn3-linux#105] opened 2022-02-06 17:42 UTC
Where's the pretty GUI for us desktop users?! What do I need to do? Write it myself? 😝

**Comment by dsommers** [comment] 2022-02-06 21:23
Yes. Alternatively, this is a duplicate of #46.  Currently we do not have any other plans for a GUI than a NetworkManager integration at some point.  If you do write a GUI, that would be awesome, please keep us updated. You only need to call some D-Bus calls from the GUI to the OpenVPN 3 Linux D-Bus services (essentially Configuration and Session Manager services) to do the same `openvpn2` and `openvpn3` command lines do.

**Closed by dsommers** 2022-02-06 21:23 UTC

**Comment by jfly** [comment] 2023-07-09 00:36
> Currently we do not have any other plans for a GUI than a NetworkManager integration at some point.

In case anyone else finds this useful, I believe this work is being tracked here: https://gitlab.gnome.org/GNOME/NetworkManager-openvpn/-/issues/69.
