### ISSUE TITLE
Not supported Debian 12 (bookworm)

### ISSUE THREAD

**Issue by VladimirParkhomenko** [OpenVPN/openvpn3-linux#201] opened 2023-08-02 15:26 UTC
https://swupdate.openvpn.net/community/openvpn3/repos/openvpn3-bookworm.list

Code: NoSuchKey
Message: The specified key does not exist.
Key: community/openvpn3/repos/openvpn3-bookworm.list
RequestId: 99VTV0M61CZR3Z64
HostId: 9qtDBtYTOm7ubVXtCYhovLeEcPIiPnxbCUZkm5fAAjDvSqX+6M+hZGLaCk9sHexyKfEUt9Dc2dA=

**Comment by dsommers** [comment] 2023-08-03 17:15
Debian 12 support will arrive with the coming v21 release.

**Comment by mdimarino** [comment] 2023-08-24 12:18
Hello, any date when v21 release will arrive?

**Comment by dsommers** [comment] 2023-08-24 18:53
@mdimarino Sorry, no ETA at the moment.  We need to resolve issue #171 first, which has potential to also cause issues on Debian 12 as well.  And I'm deep into solving that issue.

**Comment by dsommers** [comment] 2023-09-12 09:15
Closing as it is a duplicate of #193

**Closed by dsommers** 2023-09-12 09:15 UTC
Labels: duplicate, distribution-support
