### ISSUE TITLE
Could not get owner of name 'net.openvpn.v3.configuration': no such name on WSL2

### ISSUE THREAD

**Issue by muse117** [OpenVPN/openvpn3-linux#78] opened 2021-10-05 12:35 UTC
I run openvpn3-as https://192.168.127.129 on WSL2-ubuntu-20.04 and get a error that:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'net.openvpn.v3.configuration': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/openvpn3-as", line 207, in <module>
    cfgmgr = openvpn3.ConfigurationManager(sysbus)
  File "/usr/lib/python3.8/openvpn3/ConfigManager.py", line 215, in __init__
    self.__manager_object = dbuscon.get_object('net.openvpn.v3.configuration',
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.FailedToSetup: Failed to setup environment correctly

**Comment by dsommers** [comment] 2021-10-05 13:12
Can you try to run this command as root and report the output?

    # openvpn3-admin version --services

**Comment by muse117** [comment] 2021-10-05 13:53
> Can you try to run this command as root and report the output?
> 
> ```
> # openvpn3-admin version --services
> ```

OpenVPN 3 D-Bus services:

  - Client backend starter service
     openvpn3-service-backendstart: git:master:02db7f7865c8fc7e


(process:4273): GLib-GObject-CRITICAL **: 21:52:59.054: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
** ERROR ** Could not establish a connection with 'net.openvpn.v3.configuration'

**Comment by dsommers** [comment] 2021-10-05 15:44
Do you have a functional D-Bus service running?  I see you're running this inside a WSL2 environment, and so this is a completely new environment not close to normal Linux distributions.

**Comment by muse117** [comment] 2021-10-06 07:30
> Do you have a functional D-Bus service running? I see you're running this inside a WSL2 environment, and so this is a completely new environment not close to normal Linux distributions.

![微信截图_20211006151211](https://user-images.githubusercontent.com/9733486/136159119-13c8d81f-36c0-429b-9403-37335e01b09c.png)

**Comment by muse117** [comment] 2021-10-10 06:24
> Can you try these two commands and provide the output of it?
> 
> ```
> $ dbus-send --system --dest=org.freedesktop.DBus --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListActivatableNames | grep net.openvpn.v3
> $ dbus-send --system --dest=net.openvpn.v3.configuration --print-reply /net/openvpn/v3/configuration org.freedesktop.DBus.Introspectable.Introspect
> ```
> 
> The first command must return several `net.openvpn.v3.*` services. Otherwise your D-Bus setup is not correct. It could be that the service files usually installed in `/usr/share/dbus-1/system-services/net.openvpn.v3.*.service` on standard Linux distributions is not installed in the correct place on WSL2.

![微信截图_20211010141858](https://user-images.githubusercontent.com/9733486/136685148-b0ea5edd-de58-43cf-a828-076b0091330d.png)

**Comment by muse117** [comment] 2021-10-10 06:25
> Another thought hit me ... have you created the `openvpn` user and group? And does `/var/lib/openvpn3` exist and is owned + writable by the `openvpn` user and group?

![Uploading 微信截图_20211010142504.png…]()

**Comment by dsommers** [comment] 2021-10-11 13:40
The file permissions looks right and fine enough.  The list of `net.openvpn.v3.*` services is also exactly what is expected.  The introspection though looks very wrong though.  It should present much more than just and empty `<node/>`.

Can you try to run the second `dbus-send` (`[...].Introspect`) call a few times with 2-3 seconds in between and see if you get the same result?  I'm wondering if the service start-up is just too slow via WSL2.

Secondly, can you as `root` try to start this command line manually?

     /usr/libexec/openvpn3-linux/openvpn3-service-configmgr --log-level 6 --log-file stdout: --colour --idle-exit 0 --state-dir /var/lib/openvpn3

**Comment by dsommers** [comment] 2021-11-06 10:20
We have done some investigation.  The issue is related to `systemd-resolved` not being available.  In addition, the "No such file or directory" errors indicates a build from git on WSL2 without the proper `./configure` arguments.

Our test setup used an Ubuntu install in WSL2, where the [openvpn3-linux repository](https://community.openvpn.net/openvpn/wiki/OpenVPN3Linux)  was enabled and installed using `apt install openvpn3`.  Then we modified the `Exec=` line in `/usr/share/dbus-1/system-services/net.openvpn.v3.netcfg.service` to say:

     Exec=/usr/libexec/openvpn3-linux/openvpn3-service-netcfg --resolv-conf /etc/resolv.conf --state-dir "/var/lib/openvpn3"

With that in place, it was possible to start a VPN session.

Since we have this use case working, I'm closing this as openvpn3-linux is confirmed working with WSL2.

**Closed by dsommers** 2021-11-06 10:20 UTC
