### ISSUE TITLE
Add repository support for Debian 12 Bookworm

### ISSUE THREAD

**Issue by glxxyxafonso** [OpenVPN/openvpn3-linux#207] opened 2023-10-08 09:14 UTC
Hey! I was trying to install OpenVPN and got a 404, while trying to add the Bookworm repo.

`user@machine:~$ sudo curl -fsSL https://swupdate.openvpn.net/community/openvpn3/repos/openvpn3-bookworm
.list -o /etc/apt/sources.list.d/openvpn3.list`

I've also tried adding the Debian 11 repo, it did work,, but now I get this error while installing:
`user@machine:~$ sudo apt-get install python3-openvpn-connector-setup`
`Reading package lists... Done`
`Building dependency tree... Done`
`Reading state information... Done`
`Some packages could not be installed. This may mean that you have`
`requested an impossible situation or if you are using the unstable`
`distribution that some required packages have not yet been created`
`or been moved out of Incoming.`
`The following information may help to resolve the situation:`

`The following packages have unmet dependencies:`
`openvpn3 : Depends: libjsoncpp24 (>= 1.9.4) but it is not installable`
            `Depends: libssl1.1 (>= 1.1.1) but it is not installable`
            `Depends: libtinyxml2-8 (>= 8.0.0) but it is not installable`

Same thing for normal openvpn3.

`user@machine:~$ sudo apt install openvpn3`
`Reading package lists... Done`
`Building dependency tree... Done`
`Reading state information... Done`
`Some packages could not be installed. This may mean that you have`
`requested an impossible situation or if you are using the unstable`
`distribution that some required packages have not yet been created`
`or been moved out of Incoming.`
`The following information may help to resolve the situation:`

`The following packages have unmet dependencies:`
 `openvpn3 : Depends: libjsoncpp24 (>= 1.9.4) but it is not installable`
            `Depends: libssl1.1 (>= 1.1.1) but it is not installable`
            `Depends: libtinyxml2-8 (>= 8.0.0) but it is not installable`
`E: Unable to correct problems, you have held broken packages.`

Is there any type of support for Debian 12?

**Comment by dsommers** [comment] 2023-10-09 07:09
This is a duplicate of #193.  Closing as such.

**Closed by dsommers** 2023-10-09 07:09 UTC
