### ISSUE TITLE
keepalive must have at leasdt 3 arguments - docs only outline 2

### ISSUE THREAD

**Issue by paul-uz** [OpenVPN/openvpn3-linux#27] opened 2020-11-16 15:48 UTC
I am trying to use OpenVPN to connect from Github Actions to a remote server.

Using `openvpn2 --config config.ovpn --pkcs12 foo.p12 --daemon` I get the following error message:

```
 ERROR ** org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code36: GDBus.Error:net.openvpn.v3.sessions.error: Failed communicating with VPN backend: Failed calling D-Bus method Connect: GDBus.Error:net.openvpn.v3.backend.error.standard: Failed executing D-Bus call 'Connect': Configuration parsing failed: ERR_PROFILE_OPTION: option_error: option 'keepalive' must have at least 3 arguments
```

`keepalive 5 20` is defined in the `.ovpn` file.

https://github.com/OpenVPN/openvpn3-linux/blob/master/docs/man/openvpn2.1.rst#options shows that keepalive accepts 2 args.

**Comment by dsommers** [comment] 2020-11-16 20:19
This is a duplicate of issue #26.  Please have a closer look there for details.  This issue will be fixed in the coming v12_beta release.

**Closed by dsommers** 2020-11-16 20:19 UTC
Labels: duplicate

**Comment by paul-uz** [comment] 2020-11-17 09:15
@dsommers how do I fix it in the meantime?

**Comment by dsommers** [comment] 2020-11-30 16:29
> @dsommers how do I fix it in the meantime?

That is explained in comment https://github.com/OpenVPN/openvpn3-linux/issues/26#issuecomment-721405131.
