### ISSUE TITLE
on ubuntu 23.04 lts libprotobuf23 is missing

### ISSUE THREAD

**Issue by zartaz** [OpenVPN/openvpn3-linux#178] opened 2023-04-21 16:45 UTC
in order to install openvpn3-client on kubuntu 23.04 i had to download 
http://ftp.de.debian.org/debian/pool/main/p/protobuf/libprotobuf23_3.12.4-1_amd64.deb
and install it because i think a newer version is installed by default

**Comment by schwabe** [comment] 2023-04-21 16:56
Duplicate of https://github.com/OpenVPN/openvpn3-linux/issues/171 and https://github.com/OpenVPN/openvpn3-linux/issues/176 and #177

**Closed by schwabe** 2023-04-21 16:56 UTC
