### ISSUE TITLE
Fedora Silverblue session exits after 90 seconds

### ISSUE THREAD

**Issue by p5** [OpenVPN/openvpn3-linux#186] opened 2023-05-30 15:24 UTC
After around 90 seconds of being connected to OpenVPN Cloud (+ Google SSO if it helps), my session gets disconnected and the following `journalctl` error is shown:

<details>

```
May 30 16:12:35 fedora systemd-coredump[2920]: [🡕] Process 2617 (openvpn3-servic) of user 985 dumped core.
                                               
                                               Module libnss_resolve.so.2 from rpm systemd-253.4-1.fc38.x86_64
                                               Module libnss_mdns4_minimal.so.2 from rpm nss-mdns-0.15.1-8.fc38.x86_64
                                               Module libnss_myhostname.so.2 from rpm systemd-253.4-1.fc38.x86_64
                                               Module libblkid.so.1 from rpm util-linux-2.38.1-4.fc38.x86_64
                                               Module libzstd.so.1 from rpm zstd-1.5.5-1.fc38.x86_64
                                               Module liblzma.so.5 from rpm xz-5.4.1-1.fc38.x86_64
                                               Module libcap.so.2 from rpm libcap-2.48-6.fc38.x86_64
                                               Module libpcre2-8.so.0 from rpm pcre2-10.42-1.fc38.1.x86_64
                                               Module libffi.so.8 from rpm libffi-3.4.4-2.fc38.x86_64
                                               Module libselinux.so.1 from rpm libselinux-3.5-1.fc38.x86_64
                                               Module libmount.so.1 from rpm util-linux-2.38.1-4.fc38.x86_64
                                               Module libgmodule-2.0.so.0 from rpm glib2-2.76.3-1.fc38.x86_64
                                               Module libz.so.1 from rpm zlib-1.2.13-3.fc38.x86_64
                                               Module libprotobuf.so.30 from rpm protobuf-3.19.6-2.fc38.x86_64
                                               Module libnl-3.so.200 from rpm libnl3-3.7.0-3.fc38.x86_64
                                               Module libnl-genl-3.so.200 from rpm libnl3-3.7.0-3.fc38.x86_64
                                               Module libsystemd.so.0 from rpm systemd-253.4-1.fc38.x86_64
                                               Module libuuid.so.1 from rpm util-linux-2.38.1-4.fc38.x86_64
                                               Module liblz4.so.1 from rpm lz4-1.9.4-2.fc38.x86_64
                                               Module libjsoncpp.so.25 from rpm jsoncpp-1.9.5-4.fc38.x86_64
                                               Module libglib-2.0.so.0 from rpm glib2-2.76.3-1.fc38.x86_64
                                               Module libgobject-2.0.so.0 from rpm glib2-2.76.3-1.fc38.x86_64
                                               Module libgio-2.0.so.0 from rpm glib2-2.76.3-1.fc38.x86_64
                                               Module libcrypto.so.3 from rpm openssl-3.0.8-2.fc38.x86_64
                                               Module libssl.so.3 from rpm openssl-3.0.8-2.fc38.x86_64
                                               Module openvpn3-service-client from rpm openvpn3-20-2.fc38.x86_64
                                               Stack trace of thread 2617:
                                               #0  0x00007fc2f58b0844 __pthread_kill_implementation (libc.so.6 + 0x8e844)
                                               #1  0x00007fc2f585fabe raise (libc.so.6 + 0x3dabe)
                                               #2  0x00007fc2f584887f abort (libc.so.6 + 0x2687f)
                                               #3  0x00007fc2f5aa4cf9 _ZN9__gnu_cxx27__verbose_terminate_handlerEv.cold (libstdc++.so.6 + 0xa4cf9)
                                               #4  0x00007fc2f5ab4f6c _ZN10__cxxabiv111__terminateEPFvvE (libstdc++.so.6 + 0xb4f6c)
                                               #5  0x00007fc2f5ab4fd7 _ZSt9terminatev (libstdc++.so.6 + 0xb4fd7)
                                               #6  0x0000559dfdb1b3f3 _ZN19BackendClientObjectD2Ev.lto_priv.0 (openvpn3-service-client + 0xd23f3)
                                               #7  0x0000559dfdb2135c _ZN17BackendClientDBusD2Ev.lto_priv.0 (openvpn3-service-client + 0xd835c)
                                               #8  0x0000559dfdb2f3a5 _Z14client_serviceSt10shared_ptrI10ParsedArgsE (openvpn3-service-client + 0xe63a5)
                                               #9  0x0000559dfdb5d1f9 _ZN13SingleCommand10RunCommandENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjiPPc (openvpn3-service-client + 0x1141f9)
                                               #10 0x0000559dfdaae5f4 _ZN13SingleCommand10RunCommandENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiPPc (openvpn3-service-client + 0x655f4)
                                               #11 0x0000559dfdaa6d8d main (openvpn3-service-client + 0x5dd8d)
                                               #12 0x00007fc2f5849b4a __libc_start_call_main (libc.so.6 + 0x27b4a)
                                               #13 0x00007fc2f5849c0b __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x27c0b)
                                               #14 0x0000559dfdaadd65 _start (openvpn3-service-client + 0x64d65)

                                               Stack trace of thread 2618:
                                               #0  0x00007fc2f592cb5d syscall (libc.so.6 + 0x10ab5d)
                                               #1  0x00007fc2f65085ee g_cond_wait (libglib-2.0.so.0 + 0xb15ee)
                                               #2  0x00007fc2f647e04b g_async_queue_pop_intern_unlocked (libglib-2.0.so.0 + 0x2704b)
                                               #3  0x00007fc2f64e3473 g_thread_pool_spawn_thread (libglib-2.0.so.0 + 0x8c473)
                                               #4  0x00007fc2f64e1893 g_thread_proxy (libglib-2.0.so.0 + 0x8a893)
                                               #5  0x00007fc2f58ae907 start_thread (libc.so.6 + 0x8c907)
                                               #6  0x00007fc2f5934870 __clone3 (libc.so.6 + 0x112870)
                                               
                                               Stack trace of thread 2620:
                                               #0  0x00007fc2f592735d __poll (libc.so.6 + 0x10535d)
                                               #1  0x00007fc2f65113a9 g_main_context_iterate.isra.0 (libglib-2.0.so.0 + 0xba3a9)
                                               #2  0x00007fc2f64b299f g_main_loop_run (libglib-2.0.so.0 + 0x5b99f)
                                               #3  0x00007fc2f6b684b2 gdbus_shared_thread_func.lto_priv.0 (libgio-2.0.so.0 + 0x11a4b2)
                                               #4  0x00007fc2f64e1893 g_thread_proxy (libglib-2.0.so.0 + 0x8a893)
                                               #5  0x00007fc2f58ae907 start_thread (libc.so.6 + 0x8c907)
                                               #6  0x00007fc2f5934870 __clone3 (libc.so.6 + 0x112870)
                                               
                                               Stack trace of thread 2619:
                                               #0  0x00007fc2f592735d __poll (libc.so.6 + 0x10535d)
                                               #1  0x00007fc2f65113a9 g_main_context_iterate.isra.0 (libglib-2.0.so.0 + 0xba3a9)
                                               #2  0x00007fc2f64b0a23 g_main_context_iteration (libglib-2.0.so.0 + 0x59a23)
                                               #3  0x00007fc2f64b0a79 glib_worker_main (libglib-2.0.so.0 + 0x59a79)
                                               #4  0x00007fc2f64e1893 g_thread_proxy (libglib-2.0.so.0 + 0x8a893)
                                               #5  0x00007fc2f58ae907 start_thread (libc.so.6 + 0x8c907)
                                               #6  0x00007fc2f5934870 __clone3 (libc.so.6 + 0x112870)
                                               ELF object binary architecture: AMD x86-64
░░ Subject: Process 2617 (openvpn3-servic) dumped core
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ Documentation: man:core(5)
░░ 
░░ Process 2617 (openvpn3-servic) crashed and dumped core.
░░ 
░░ This usually indicates a programming error in the crashing program and
░░ should be reported to its vendor as a bug.
```

</details>

This shows after Google SSO is authenticated, and the connection shows as "Connected" in the OpenVPN Cloud UI for a short amount of time.

Unfortunately `openvpn3 log` shows nothing.  
This is **not** using the new DCO feature.

Please let me know what else I can provide as I understand just the core dump isn't very useful.

**Comment by dsommers** [comment] 2023-05-31 16:10
I suspect this is related to glib2-2.76 and newer.  This is a known issue which is being worked on; see issue #171 for more details.

**Comment by dsommers** [comment] 2023-07-03 10:49
Closing this as a duplicate of #171.

**Closed by dsommers** 2023-07-03 10:49 UTC
