### ISSUE TITLE
 Ubuntu 23.10 - Failed to execute program net.openvpn.v3.sessions: Permission denied error persists.

### ISSUE THREAD

**Issue by Marietto2008** [OpenVPN/openvpn3-linux#231] opened 2024-01-29 15:31 UTC
Hello.

Here on github I see the bad habit to close the tickets very soon,before to have reached a good number of positive reviews. I think it's not good. Anyway,I have reopened this bug report :

https://github.com/OpenVPN/openvpn3-linux/issues/214

that should have been fixed,but I still see it on Ubuntu 23.10 :

```
root@Z390-AORUS-PRO-DEST:/home/ziomario/Scrivania# sudo add-apt-repository ppa:djpig/openvpn

root@Z390-AORUS-PRO-DEST:/home/ziomario/Scrivania# sudo apt update

root@Z390-AORUS-PRO-DEST:/home/ziomario/Scrivania# sudo apt upgrade

root@Z390-AORUS-PRO-DEST:/home/ziomario/Scrivania# openvpn3 session-start --dco true --config vpn.aus.iamthebestvpn.net.ovpn  

** ERROR ** Failed preparing proxy: Error calling StartServiceByName for net.openvpn.v3.sessions: Failed to execute program net.openvpn.v3.sessions: Permission denied
```

**Comment by dsommers** [comment] 2024-01-30 10:25
Closed as duplicate of #214.

**Closed by dsommers** 2024-01-30 10:25 UTC
Labels: duplicate
